server:
  port: 10011

spring:
  application:
    name: dataStructure
  datasource:
    url: jdbc:mysql://119.29.187.18:3306/db_tfx?serverTimezone-UTC
    username: root
    password: tfx12138
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/tfxing/dataStructure/dao/*.xml

